### ISSUE TITLE
ImportError: No module named local_settings

### ISSUE THREAD

**Issue by teddyding** [thinkfoss/website#5]
Hi, 

I'm trying to run this git project locally, and after I cloned the project and ran "python manage.py runserver" it gives me this error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/teddyding/Projects/thinkfoss/website/thinkfoss/settings.py", line 141, in <module>
    from local_settings import *
ImportError: No module named local_settings
```

Should this local_settings file be provided by myself? Thanks for your time in advance!

**Comment by tonythomas01** [comment]
You have to run the following in https://github.com/thinkfoss/website/blob/master/docs/INSTALL.md#setup-database for it to work!
